export const LogoCategory = {
  Tendances: 'Tendances',
  Football: 'Football',
  Tennis: 'Tennis',
  Natation: 'Natation',
  BasketBall: 'Basket-ball',
  Athletisme: 'Athlétisme',
  Rugby: 'Rugby',
  Judo: 'Judo',
  Cyclisme: 'Cyclisme',
  Escrime: 'Escrime',
  Handball: 'Handball',
  Gymnastique: 'Gymnastique',
  Volleyball: 'Volley-ball',
  Equitation: 'Équitation',
  SuperHeros: 'Super-héros',
  Animaux: 'Animaux',
  Chevalier: 'Chevalier',
  Nourriture: 'Nourriture',
  Musique: 'Musique',
  Voyage: 'Voyage',
  Espace: 'Espace',
  Fantaisie: 'Fantaisie',
  DessinsAnimes: 'Dessins animés',
  Universite: 'Université',
};
